### ISSUE TITLE
Unable to install because of CUDA version

### ISSUE THREAD

**Issue by egolep** [dfdx/Avalon.jl#9]
If I try to install Avalon, I get this error:

ERROR: Unsatisfiable requirements detected for package CUDA [052768ef]:
 CUDA [052768ef] log:
 ├─possible versions are: 0.1.0-3.4.2 or uninstalled
 ├─restricted by julia compatibility requirements to versions: [2.3.0, 2.5.0-3.4.2] or uninstalled
 └─restricted by compatibility requirements with Avalon [d462d321] to versions: 1.2.1-1.3.3 — no versions left
   └─Avalon [d462d321] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0

I get this even on a new, blank environment.

I'm using julia 1.6.2 on Manjaro Linux. CUDA is V11.4.100, if that matters.

**Comment by dfdx** [comment]
Thanks for reporting this. It looks like the whole stack that Avalon is based on got a set of backward-incompatible changes since the release of Julia 1.6 :disappointed: I'll try to update it over the next week. Meanwhile, you should be able to play around with Avalon on Julia 1.4 and switch to the current Julia version once I finish the migration (no code changes on your side are expected).

**Comment by dfdx** [comment]
Sorry for the delay, the ecosystem has moved significantly farther than I expected, so lots of code had to be updated. Currently, the only issue left is that NLL loss fails of GPU due to mcabbott/Tullio.jl#128. Besides this issue, everything seems to work on Julia 1.6 with CUDA 3. If it's still relevant to you, the latest code is available in the `cuda-3` branch.

**Comment by dfdx** [comment]
I just published Avalon v0.2.0 with full support for Julia 1.6 and CUDA 3.
